#!/usr/bin/env zsh

reconstruction_file="$PWD/results/production/reconstruction"
mkdir -p "$(dirname "$reconstruction_file")"
echo '' >"$reconstruction_file"

# ------------------------------------------------------------------------------
# Baselines; location = United States; seed = 140
# ------------------------------------------------------------------------------

# Naive persistence model
echo '- Naive Persistence Model' | tee -a "$reconstruction_file"
auda pipe run \
    "-p TF-Z-NORM:on=test_set -> AD-IF:on=normalized_dataset -> 
    MD-NAIVE:on=inlier_dataset" \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    EV-NORMAL:pipe=\@0 \
    --names=mae,rmse,r2,mape |
    tee -a "$reconstruction_file"

# Drift model
echo '- Drift Model' | tee -a "$reconstruction_file"
auda pipe run \
    "-p TF-Z-NORM:on=test_set -> AD-IF:on=normalized_dataset -> 
    MD-DRIFT:on=inlier_dataset" \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    EV-NORMAL:pipe=\@0 \
    --names=mae,rmse,r2,mape |
    tee -a "$reconstruction_file"

# Exponential smoothing
echo '- Exponential Smoothing' | tee -a "$reconstruction_file"
auda pipe run \
    "-p TF-Z-NORM:on=test_set -> AD-IF:on=normalized_dataset -> 
    MD-ETS:on=inlier_dataset" \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    EV-NORMAL:pipe=\@0 \
    --names=mae,rmse,r2,mape |
    tee -a "$reconstruction_file"

# ------------------------------------------------------------------------------
# Test with Best Hyperparameters; location = "United States"; metric = MAPE;
# seed = 140; training_portion = 0.7; should_shuffle = 0
#
# See modules/testing/reconstruction for the best hyperparameters
# ------------------------------------------------------------------------------

# Polynomial regression
# [Hyperparameters] degree = 2
echo '- Polynomial Regression' | tee -a "$reconstruction_file"
auda pipe run \
    "-p TF-Z-NORM:on=test_set -> AD-IF:on=normalized_dataset -> 
    MD-PR:on=inlier_dataset;degree=2" \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    EV-NORMAL:pipe=\@0 \
    --names=mae,rmse,r2,mape |
    tee -a "$reconstruction_file"

# Polynomial Ridge regression
# [Hyperparameters] degree = 3, alpha = 14.487
echo '- Ridge Regression' | tee -a "$reconstruction_file"
auda pipe run \
    "-p TF-Z-NORM:on=test_set -> AD-IF:on=normalized_dataset -> 
    MD-PRR:on=inlier_dataset;degree=3;alpha=14.487" \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    EV-NORMAL:pipe=\@0 \
    --names=mae,rmse,r2,mape |
    tee -a "$reconstruction_file"

# Gaussian Process Regression
# [Hyperparameters] length_scale = 55.911, noise_level = 6.487
echo '- Gaussian Process Regression' | tee -a "$reconstruction_file"
auda pipe run \
    "-p TF-Z-NORM:on=test_set -> AD-IF:on=normalized_dataset -> 
    MD-GPR:on=inlier_dataset;length_scale=158.016;noise_level=6.093" \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    EV-NORMAL:pipe=\@0 \
    --names=mae,rmse,r2,mape |
    tee -a "$reconstruction_file"

# Support Vector Regression
# [Hyperparameters] C = 72.281, epsilon = 0.002
echo '- Support Vector Regression' | tee -a "$reconstruction_file"
auda pipe run \
    "-p TF-Z-NORM:on=test_set -> AD-IF:on=normalized_dataset -> 
    MD-SVR:on=inlier_dataset;c=72.281;epsilon=0.002" \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    EV-NORMAL:pipe=\@0 \
    --names=mae,rmse,r2,mape |
    tee -a "$reconstruction_file"

# ------------------------------------------------------------------------------
# Make tables
# ------------------------------------------------------------------------------

reconstruction_table_file="$PWD/results/tables/reconstruction"
python "$PWD/modules/script/make_table.py" \
    "$reconstruction_file" \
    "$reconstruction_table_file"

# ------------------------------------------------------------------------------
# Generate plots for ML models
# ------------------------------------------------------------------------------

reconstruction_plots_dir="$PWD/results/plots/reconstruction"
mkdir -p "$(dirname "$reconstruction_file")"

# Polynomial regression
auda pipe run \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    TF-Z-NORM:on=training_set \
    MD-PR:on=normalized_dataset\;degree=2 \
    PL-PR:on=training_set \
    PL-SAVE:path="$reconstruction_plots_dir/pr.png"

# Polynomial Ridge regression
auda pipe run \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    TF-Z-NORM:on=training_set \
    MD-PRR:on=normalized_dataset\;degree=3\;alpha=14.487 \
    PL-PRR:on=training_set \
    PL-SAVE:path="$reconstruction_plots_dir/prr.png"

# Gaussian Process Regression
auda pipe run \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    TF-Z-NORM:on=training_set \
    MD-GPR:on=normalized_dataset\;degree=2 \
    PL-GPR:on=training_set \
    PL-SAVE:path="$reconstruction_plots_dir/gpr.png"

# Support Vector Regression
auda pipe run \
    DS-YEAR-PW:location=United\ States \
    PP-SORT:on=dataset\;sort_by_feature_index=0 \
    PP-SPLIT:on=sorted_dataset\;training_portion=0.7\;seed=140 \
    TF-Z-NORM:on=training_set \
    MD-SVR:on=normalized_dataset\;c=72.281\;epsilon=0.002\;seed=140 \
    PL-SVR:on=training_set \
    PL-SAVE:path="$reconstruction_plots_dir/svr.png"
