#!/usr/bin/env zsh

set -euo pipefail

reconstruction_file="$PWD/results/production/reconstruction"
mkdir -p "$(dirname "$reconstruction_file")"
echo '' >"$reconstruction_file"

location="United States"
seed="140"

auda pipe run \
    "-p HT-SVR:metric=mape;use_time_series=1;num_k_folds=4" \
    "-p TF-Z-NORM:on=training_set -> MD-SVR:on=normalized_dataset" \
    "DS-YEAR-PW:location=$location;seed=$seed" \
    EV-RO:on=dataset\;ht_pipe=\@0\;training_pipe=\@1 \
    --names=mae,rmse,r2,mape |
    tee -a "$reconstruction_file"
